<a href="https://colab.research.google.com/github/kendi361/Basic-Calculator-Program/blob/main/Copy_of_Untitled20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('Uganda_Karamoja_District_Crop_Yield_Population.csv')
df = pd.read_csv('Uganda_Karamoja_Subcounty_Crop_Yield_Population.csv')

In [ ]:
print(df.isnull().sum())

OBJECTID          0
SUBCOUNTY_NAME    0
DISTRICT_NAME     0
POP               0
Area              0
Karamoja          0
S_Yield_Ha        0
M_Yield_Ha        0
Crop_Area_Ha      0
S_Area_Ha         0
M_Area_Ha         0
S_Prod_Tot        0
M_Prod_Tot        0
dtype: int64

In [ ]:
df.head(10)

,OBJECTID,SUBCOUNTY_NAME,DISTRICT_NAME,POP,Area,Karamoja,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,263,KACHERI,KOTIDO,17244,1067176155,Y,354.207411,1137.467019,7023.533691,6434.342449,528.124229,2.279092e+06,600723.892900
1,264,KOTIDO,KOTIDO,52771,597575188,Y,367.890523,1162.996687,13587.990760,12455.592640,824.767081,4.582294e+06,959201.382500
2,265,KOTIDO TOWN COUNCIL,KOTIDO,27389,23972401,Y,369.314177,1167.005832,1656.531855,1520.322052,8.561644,5.614765e+05,9991.488268
3,266,NAKAPERIMORU,KOTIDO,38775,419111591,Y,283.324569,852.366578,7087.823334,6761.488901,45.721712,1.915696e+06,38971.659080
4,267,PANYANGARA,KOTIDO,65704,880955930,Y,373.836926,1283.859882,10398.249390,10111.198130,172.611914,3.779939e+06,221609.511400
5,268,RENGEN,KOTIDO,41273,652744859,Y,271.185843,1047.180128,13278.520430,12964.499730,171.585704,3.515789e+06,179681.139000
6,591,KAABONG EAST,KAABONG,42221,60801942,Y,160.588525,650.123565,1021.316990,1004.647534,15.660409,1.613349e+05,10181.201000
7,592,KAABONG TOWN COUNCIL,KAABONG,38857,13071455,Y,212.210703,1229.213444,175.080527,156.503888,18.526186,3.321180e+04,22772.636430
8,593,KAABONG WEST,KAABONG,41454,67612362,Y,208.040518,1056.416068,967.336727,910.254122,56.275355,1.893697e+05,59450.189420
9,594,KALAPATA,KAABONG,99203,223116860,Y,209.809352,633.423182,2834.349905,2501.368282,331.225795,5.248105e+05,209806.097000

In [ ]:
df.tail(10)

,OBJECTID,SUBCOUNTY_NAME,DISTRICT_NAME,POP,Area,Karamoja,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
42,1024,LOPEEI,NAPAK,18815,790782350,Y,108.156411,1053.257168,3120.318045,2121.747320,955.264617,229480.57590,1.006139e+06
43,1025,LORENGECORA,NAPAK,2503,118997955,Y,184.081197,841.815010,1031.196285,672.121886,358.550335,123725.00130,3.018331e+05
44,1026,LOTOME,NAPAK,17834,125857565,Y,128.555598,507.907068,1849.966589,1770.358693,78.035892,227589.51980,3.963498e+04
45,1027,MATANY,NAPAK,29495,338252511,Y,130.007687,497.353282,2990.847377,2664.796115,288.329571,346443.97860,1.434017e+05
46,1028,NAPAK TOWN COUNCIL,NAPAK,8010,150906375,Y,175.828068,725.813930,792.249273,386.158033,401.173442,67897.42082,2.911773e+05
47,1029,NGOLERIET,NAPAK,20790,158887552,Y,134.084089,528.699822,1215.227445,1145.339875,68.124005,153571.85410,3.601715e+04
48,1295,NYAKWAE,ABIM,16470,769609687,Y,329.759030,779.225031,792.898789,342.816838,331.111340,113046.94800,2.580102e+05
49,1313,LOKOPO,NAPAK,23200,1794470536,Y,120.862232,748.829862,6471.047334,5830.549392,553.543123,704693.21440,4.145096e+05
50,1318,RUPA,MOROTO,41493,2069554899,Y,114.270921,699.334309,2217.290717,1989.119508,222.838881,227298.51840,1.558389e+05
51,1320,MORUITA,NAKAPIRIPIRIT,16588,839293722,Y,430.557375,1248.955812,1161.390229,185.283445,959.671162,79775.15368,1.198587e+06

In [ ]:
print(df['M_Yield_Ha'].sum())

48893.4967171

In [ ]:
print(df['S_Yield_Ha'].sum())

14256.601065099998

In [ ]:
import pandas as pd
from scipy import stats

df = pd.read_csv('/content/Uganda_Karamoja_Subcounty_Crop_Yield_Population.csv')

sorghum = df["S_Yield_Ha"].dropna()
maize = df["M_Yield_Ha"].dropna()

t_stat, p_val = stats.ttest_ind(sorghum, maize, equal_var=False)

print("t-statistic:", t_stat)
print("p-value:", p_val)

alpha = 0.05
if p_val < alpha:
    print("Reject H0: Sorghum and maize yields are significantly different.")
else:
    print("Fail to reject H0: No significant difference in yields.")

t-statistic: -14.011852622032855
p-value: 2.9515543187263105e-21
Reject H0: Sorghum and maize yields are significantly different.